### ISSUE TITLE
Snapcraft: Update Go/golang example to use core22

### ISSUE THREAD

**Issue by degville** [canonical/open-documentation-academy#2]
Update the following how-to guide to use core22 (or core24):

https://snapcraft.io/docs/go-applications

## Background

Snapcraft's platform [quickstart how-to guides](https://snapcraft.io/docs/creating-a-snap) help snap developers create a first snap with their chosen framework or development environment. Many of these guides become out of date and need to be revised. Specifically, they may need to be updated to address the following:

- update the core snap to the latest supported (such as from core18 to core22)
- an updated core will typically require changes to the associated plugin
- replace an inappropriate or no longer relevant example

## Prerequisites

You will need some experience building snaps, and some knowledge of the target framework or development environment.

See also [Contribute to our documentation](https://snapcraft.io/docs/contribute-to-docs).

**Comment by activus-d** [comment]
@degville I've been reluctant to work on Snapcraft issues since I don't have the prerequisites. However, I am willing to learn and give this a go. Also, the docs are hosted on Discourse, and I'm not yet at the level needed to edit docs on Discourse. If possible, I can work on this in a markdown file and make a PR in this repository.

**Comment by degville** [comment]
@activus-d Hello! Thanks so much for your interest in this, and for your willingness to learn a little about snaps. I'd be more than happy to help if you encounter problems, but a good place to start is with the [Create a new snap](https://snapcraft.io/docs/create-a-new-snap) tutorial. If you do go through this, make a note of anything that doesn't make sense - this will really help as we'll be able to update our docs with your feedback.

And of course, I'll move the document over to this repository so you can more easily work on it here.

**Comment by degville** [comment]
I've now merged the Go How-to into this repository with #66.

**Comment by activus-d** [comment]
@degville I have gone through the tutorial and noted some aspects that may require more clarity.

First, in the "Install the snap in developer mode" section, there's no direct instruction to exit the Build environment's shell before rebuilding the snap. I believe directly instructing the users to exit the shell is important because the succeeding command, `snapcraft`, can run within the shell.

Second, I find it hard to understand the sentence "Using the location of the binary, and to permit access, it needs to be declared within an app: section of the snapcraft.yaml:" in the "Create an app section" section. Perhaps making the sentence more direct can be helpful.

Third, in the "Missing dependencies" section, it may be helpful to have the whole part section within the code block, just like the command sample in the "System access" section:

```
parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: python
    source-type: git
    source: https://github.com/liquidctl/liquidctl
    stage-packages:
       - python3-usb
```

Finally, I followed the instructions in the "Missing dependencies" section and inserted a USB device. However, I did not get any output indicating that the snap can now detect the USB device.

**Comment by degville** [comment]
Hello @activus-d. Sorry for the long delay getting back to you. I've just reviewed your PR  and given it a +1 - thank you so much for going to such lengths with this. 

I also agree with your comments on the Create a new snap tutorial. I'll create a new Academy issue for this (you have first refusal on this, but please don'e feel obliged to take it on). On the USB device debugging - you're right. We could add a more detailed set of suggestions for debugging missing dependencies.

**Comment by activus-d** [comment]
@degville Thanks for the updates. Yes, I would be happy to take up the task of updating the tutorial, so please go ahead and assign the issue to me.

**Comment by degville** [comment]
I've just tested the new yaml and the resultant snap, and updated the original forum documentation from their work. This task is now complete. Huge thank you to @activus-d for their work on updating this Goloang example.
