### ISSUE TITLE
Snapcraft: Clarify dump plugin reference

### ISSUE THREAD

**Issue by akcano** [canonical/open-documentation-academy#96]
Update the following guide:

[The dump plugin](https://snapcraft.io/docs/dump-plugin)

# Background

The documentation for the dump plugin references common Snapcraft keywords like 'organise' or 'filesets' that are used in the example, but doesn't explain the resulting behaviour and the choices that go into creating a specific layout.

# Prerequisites

Familiarity with Snapcraft or snaps is needed to understand the content and test any conjectures. The documentation is Discourse-hosted, so some experience with Discourse is also a plus.

**Comment by userMaximilian** [comment]
Hi @akcano - I would be happy to take this issue on. It looks fairly straightforward, so I *should* be able to prepare a first draft relatively quickly.

**Comment by userMaximilian** [comment]
Hi @akcano,

I realised that I didn't comment here when I raised my pull request (#121) so I'm not sure if you were ever notified about the PR. (My apologies!)

I was just browsing the Snapcraft forum when I noticed that medubelko had updated the dump plugin page a few days ago, so my version is now largely redundant. I'm more than happy for it (and this issue) to be closed off, unless you think otherwise.

**Comment by dilyn-corner** [comment]
I left this as a review on the PR, but I think it's worth cross-posting here as the PR *does* tackle what this issue specifies:

> the dump plugin is the simplest plugin that isn't a no-op, and this page doesn't need to bother itself with the whys or hows of doing file filtering. I think it only needs to explain what the dump plugin does, and link to useful resources on why it may be necessary (see my final comment in this review on creating a new file filtering doc page).
